services:
  screenguru:
    image: ghcr.io/q0wqex/screenguru:main
    hostname: screenguru
    container_name: screenguru
    ports:
      - "127.0.0.1:8000:8000"
    volumes:
      - ./data:/data
    environment:
      - MAX_FILE_SIZE_MB=10
      - CLEANUP_DURATION_HOURS=720
    restart: unless-stopped
